# Generated by Django 5.0.4 on 2024-05-22 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('img', models.ImageField(blank=True, upload_to='category_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Chart_Type',
            fields=[
                ('ids', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('name2', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkv', models.CharField(max_length=100, null=True)),
                ('reg', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=100, null=True)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('msg', models.CharField(blank=True, max_length=10000, null=True)),
                ('replied', models.CharField(blank=True, max_length=100, null=True)),
                ('msg_replied', models.CharField(blank=True, max_length=10000, null=True)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit', models.ImageField(null=True, upload_to='home_icon/')),
                ('comment', models.ImageField(null=True, upload_to='home_icon/')),
                ('delete', models.ImageField(null=True, upload_to='home_icon/')),
                ('like', models.ImageField(null=True, upload_to='home_icon/')),
                ('back', models.ImageField(null=True, upload_to='home_icon/')),
                ('image', models.ImageField(null=True, upload_to='home_icon/')),
                ('audio', models.ImageField(null=True, upload_to='home_icon/')),
                ('video', models.ImageField(null=True, upload_to='home_icon/')),
            ],
        ),
        migrations.CreateModel(
            name='Icon2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggest', models.ImageField(null=True, upload_to='home_icon/')),
                ('inbox', models.ImageField(null=True, upload_to='home_icon/')),
                ('outbox', models.ImageField(null=True, upload_to='home_icon/')),
                ('inprivate', models.ImageField(null=True, upload_to='home_icon/')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkv', models.CharField(max_length=100, null=True)),
                ('reg', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=100, null=True)),
                ('like', models.CharField(blank=True, max_length=100, null=True)),
                ('replied', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('pkv', models.IntegerField(primary_key=True, serialize=False)),
                ('cat', models.CharField(max_length=100, null=True)),
                ('reg', models.CharField(max_length=100, null=True)),
                ('identity', models.CharField(max_length=100, null=True)),
                ('msg', models.CharField(blank=True, max_length=10000)),
                ('reply', models.CharField(blank=True, max_length=10000)),
                ('no_comments', models.CharField(max_length=100, null=True)),
                ('no_likes', models.CharField(max_length=100, null=True)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='proof_screenshot/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='proof_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='proof_images2/')),
                ('video', models.FileField(blank=True, null=True, upload_to='proof_video/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='proof_audio/')),
                ('time', models.TimeField(auto_now=True, null=True)),
                ('timestamp', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('img', models.ImageField(blank=True, upload_to='option_images/')),
                ('location', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Replys',
            fields=[
                ('pkv', models.IntegerField(primary_key=True, serialize=False)),
                ('reply', models.CharField(blank=True, max_length=10000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='admin_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='admin_video/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='admin_audio/')),
                ('time', models.TimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('program', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='user_icon_images/')),
            ],
        ),
    ]
